# Generated by Django 3.2.5 on 2021-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.CharField(max_length=9)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('item_amount', models.DecimalField(decimal_places=0, max_digits=4)),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='sign',
            name='account',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
