# Generated by Django 3.2.5 on 2021-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.CharField(max_length=9)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('item_amount', models.DecimalField(decimal_places=0, max_digits=4)),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='sign',
            name='account',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='UserDATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=3)),
                ('address2', models.CharField(max_length=6)),
                ('address3', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=10)),
                ('card_name', models.CharField(max_length=50)),
                ('card_number1', models.CharField(max_length=4)),
                ('card_number2', models.CharField(max_length=4)),
                ('card_number3', models.CharField(max_length=4)),
                ('card_number4', models.CharField(max_length=4)),
                ('card_date1', models.CharField(max_length=2)),
                ('card_date2', models.CharField(max_length=2)),
                ('card_CVC', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='sign',
        ),
    ]
