# Generated by Django 3.2.5 on 2021-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210801_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_tpye',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
