# Generated by Django 3.2.5 on 2021-08-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210801_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='account',
            new_name='username',
        ),
    ]
